spring:
  jpa:
    show-sql: true
  data:
    jpa:
      repositories:
        enabled: true
  liquibase:
    enabled: true
    change-log: classpath:/db-migration/changelog.xml

server:
  port: 8089

alex:
  datasource:
    jdbcUrl: jdbc:h2:mem:test;
    user: test
    password: test
    driverClass: org.h2.Driver